### ISSUE TITLE
Can't launch dappeteer on Ubuntu 22

### ISSUE THREAD

**Issue by yaelahda** [ChainSafe/dappeteer#286]
**Describe the bug**
another puppeteer script is normal run, but dappeteer can't launch

**Logs**
```shell
Some Logs from console
```

**Screenshots**
![image](https://user-images.githubusercontent.com/73057168/219543515-1a49ac7a-e9a5-4844-a7b5-80d384bba66a.png)

**System:**
- OS: Ubuntu
- OS version 22.04.1 LTS
- NodeJs version 18.14.0
- dappeteer version 5.0.0
- puppeteer version 19.7.1

**Comment by greyireland** [comment]
+1
```

        Running tests on MetaMask version v10.25.0 
        Flask version: false, 
        Headless: true
        

Getting MetaMask  extension version: v10.25.0
extension stored in directory: /Users/greyireland/vscode/dappetter/node_modules/.cache/.metamask
downloaded files stored in: /Users/greyireland/vscode/dappetter/node_modules/.cache/.metamask/download 

Searching for MetaMask release
Found requested MetaMask release
Found requested MetaMask release
Downloading MetaMask release
Download successful
Unpacking release
Unpack successful
node:internal/modules/cjs/loader:1060
  const err = new Error(message);
              ^

Error: Cannot find module 'puppeteer'
Require stack:
- /Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/puppeteer.js
- /Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/launch.js
- /Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/index.js
- /Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/index.js
- /Users/greyireland/vscode/dappetter/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at /Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/puppeteer.js:28:77
    at async launchPuppeteer (/Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/puppeteer.js:28:29)
    at async launch (/Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/launch.js:63:24)
    at async Object.bootstrap (/Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/index.js:26:21)
    at async main (/Users/greyireland/vscode/dappetter/main.js:6:33) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/puppeteer.js',
    '/Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/launch.js',
    '/Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/setup/index.js',
    '/Users/greyireland/vscode/dappetter/node_modules/@chainsafe/dappeteer/dist/index.js',
    '/Users/greyireland/vscode/dappetter/main.js'
  ]
}

Node.js v19.6.0

```

**Comment by greyireland** [comment]
npm install puppeteer --legacy-peer-deps

**Comment by greyireland** [comment]
```
  "devDependencies": {
    "puppeteer": "19.7.1"
  }
```
npm install -D --legacy-peer-deps

**Comment by BeroBurny** [comment]
Thanks for reaching out.

Unfortunately is hard to understand the state of an application without reproducing steps or any snippets.
Can you clone this repo https://github.com/BeroBurny/dappeteer-jest follow the steps from readme and reach back to us with the result?

**Comment by yaelahda** [comment]
> 

root@ACEFountain:~/dappeteer-jest# yarn test
yarn run v1.22.19
$ jest
  console.log
    
            Running tests on MetaMask version v10.25.0 
            Flask version: false, 
            Headless: true

      at launch (node_modules/@chainsafe/dappeteer/dist/setup/launch.js:39:21)

  console.log
    undefined

      at launch (node_modules/@chainsafe/dappeteer/dist/setup/launch.js:44:17)

  console.log
    Getting MetaMask  extension version: v10.25.0

      at Object.<anonymous>.exports.default (node_modules/@chainsafe/dappeteer/dist/setup/utils/metaMaskDownloader.js:44:13)

  console.log
    extension stored in directory: /root/dappeteer-jest/node_modules/.cache/.metamask

      at Object.<anonymous>.exports.default (node_modules/@chainsafe/dappeteer/dist/setup/utils/metaMaskDownloader.js:45:13)

  console.log
    downloaded files stored in: /root/dappeteer-jest/node_modules/.cache/.metamask/download

      at Object.<anonymous>.exports.default (node_modules/@chainsafe/dappeteer/dist/setup/utils/metaMaskDownloader.js:46:13)

  console.log
    Found already available extension files - skipping download

      at Object.<anonymous>.exports.default (node_modules/@chainsafe/dappeteer/dist/setup/utils/metaMaskDownloader.js:54:21)

 FAIL  tests/dappetter.test.ts
  ✕ dappeteer browser starts (313 ms)

  ● dappeteer browser starts

    Failed to launch the browser process!
    [46733:46733:0218/064302.238018:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

      at onClose (node_modules/puppeteer-core/src/node/BrowserRunner.ts:330:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.182 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@ACEFountain:~/dappeteer-jest#

**Comment by yaelahda** [comment]
> 

![image](https://user-images.githubusercontent.com/73057168/219845809-a735b1a0-7bca-441a-9723-f0c4377b1228.png)

**Comment by BeroBurny** [comment]
The error message says you cannot run as `root` without the `--no-sandbox` arg.
It is generally not recommended to run applications as `root`. You can try to run as a regular user or to use no sandbox argument.
You can find the arguments for a launch [here](https://github.com/ChainSafe/dappeteer/blob/master/docs/API.md#dappeteerlaunchoptions-dappeteerlaunchoptions-promisedappeteerbrowser).

Can you please try to add these arguments to a `bootstrap` and get back to is solved issue with a root?
```
puppeteerOptions: {
  args: ['--no-sandbox']
}
```

It should look like this
```typescript
const { browser } = await bootstrap({
  metaMaskVersion: RECOMMENDED_METAMASK_VERSION,
  automation: "puppeteer",
  headless: true,
  metaMaskFlask: false,
  puppeteerOptions: {
    args: ['--no-sandbox']
  }
});
```

**Comment by hongda3141** [comment]
> Thanks for reaching out.
> 
> Unfortunately is hard to understand the state of an application without reproducing steps or any snippets. Can you clone this repo https://github.com/BeroBurny/dappeteer-jest follow the steps from readme and reach back to us with the result?

Hi, I tried to run the example code of the repo https://github.com/BeroBurny/dappeteer-jest , but get an error like this:
![Screenshot from 2023-03-01 23-19-12](https://user-images.githubusercontent.com/25719952/222182858-01ef8db4-016f-49fa-8278-d5e2e4a6c9c3.png)
and when I config headless=false, it looks like the reason for that error is the metamask in chromium is stuck at the start page, like this:
![Screenshot from 2023-03-01 23-18-33](https://user-images.githubusercontent.com/25719952/222183810-a9939cc1-1025-42fa-8605-cad228dfa5d1.png)

**Comment by hongda3141** [comment]
> > Thanks for reaching out.
> > Unfortunately is hard to understand the state of an application without reproducing steps or any snippets. Can you clone this repo https://github.com/BeroBurny/dappeteer-jest follow the steps from readme and reach back to us with the result?
> 
> Hi, I tried to run the example code of the repo https://github.com/BeroBurny/dappeteer-jest , but get an error like this: ![Screenshot from 2023-03-01 23-19-12](https://user-images.githubusercontent.com/25719952/222182858-01ef8db4-016f-49fa-8278-d5e2e4a6c9c3.png) and when I config headless=false, it looks like the reason for that error is the metamask in chromium is stuck at the start page, like this: ![Screenshot from 2023-03-01 23-18-33](https://user-images.githubusercontent.com/25719952/222183810-a9939cc1-1025-42fa-8605-cad228dfa5d1.png) I'm confused about how to fix this error, metamask runs well when dappeteer version is 3.0.0, thanks a lot for some advice
> 
> **System:**
> 
> OS: Ubuntu OS version 20.04.1 LTS NodeJs version 16.19.1 dappeteer version 5.0.1 puppeteer version 19.7.1
> 
> In addition, when I am in kali system, it can run successfully, but my operation is the same. I guess the problem is related to how to start chronium/metamask, but I don't know how to fix it, especially since there is no difference in operation and code.

 Fixed it by using a faster network, thanks for supporting
