### ISSUE TITLE
Can't install both @chainsafe/dappeteer and puppeteer

### ISSUE THREAD

**Issue by MagicalBomb** [ChainSafe/dappeteer#290]
**Describe the problem**
I have installed @chainsafe/dappeteer using `npm install -s @chainsafe/dappeteer`. but I can't install pupeteer, it always told me there is error

**System:**
- OS: MacOS
- OS version 13.1 (22C65)
- NodeJs version v19.6.1
- dappeteer version 5.0.0
- puppeteer version latest

**Here are complete log generated by npm**
```
0 verbose cli /Users/maoxiandaozhenhaowan/.nvm/versions/node/v19.6.1/bin/node /Users/maoxiandaozhenhaowan/.nvm/versions/node/v19.6.1/bin/npm
1 info using npm@9.5.0
2 info using node@v19.6.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/maoxiandaozhenhaowan/.nvm/versions/node/v19.6.1/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/maoxiandaozhenhaowan/Desktop/Code/auto-blur/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/maoxiandaozhenhaowan/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/maoxiandaozhenhaowan/.nvm/versions/node/v19.6.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 3ms
17 timing npm:load:configload Completed in 3ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install puppeteer@latest
21 verbose argv "install" "puppeteer@latest"
22 timing npm:load:setTitle Completed in 5ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/maoxiandaozhenhaowan/.npm/_logs/2023-02-22T03_14_25_629Z-
26 verbose logfile /Users/maoxiandaozhenhaowan/.npm/_logs/2023-02-22T03_14_25_629Z-debug-0.log
27 timing npm:load:logFile Completed in 2ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 14ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 21ms
35 timing arborist:ctor Completed in 0ms
36 http fetch GET 200 https://registry.npmjs.org/puppeteer 16ms (cache hit)
37 timing idealTree:userRequests Completed in 23ms
38 silly idealTree buildDeps
39 silly fetch manifest puppeteer@19.7.2
40 silly placeDep ROOT puppeteer@19.7.2 OK for: auto-blur@1.0.0 want: 19.7.2
41 silly fetch manifest cosmiconfig@8.0.0
42 silly fetch manifest https-proxy-agent@5.0.1
43 silly fetch manifest progress@2.0.3
44 silly fetch manifest proxy-from-env@1.1.0
45 silly fetch manifest puppeteer-core@19.7.2
46 http fetch GET 200 https://registry.npmjs.org/cosmiconfig 33ms (cache hit)
47 http fetch GET 200 https://registry.npmjs.org/progress 935ms (cache revalidated)
48 http fetch GET 200 https://registry.npmjs.org/proxy-from-env 936ms (cache revalidated)
49 http fetch GET 200 https://registry.npmjs.org/puppeteer-core 938ms (cache revalidated)
50 http fetch GET 200 https://registry.npmjs.org/https-proxy-agent 967ms (cache revalidated)
51 timing idealTree:#root Completed in 970ms
52 silly fetch manifest puppeteer@>19
53 silly placeDep ROOT puppeteer@ REPLACE for: @chainsafe/dappeteer@5.0.0 want: >19
54 warn ERESOLVE overriding peer dependency {
54 warn ERESOLVE   code: 'ERESOLVE',
54 warn ERESOLVE   edge: {
54 warn ERESOLVE     type: 'peerOptional',
54 warn ERESOLVE     name: 'puppeteer',
54 warn ERESOLVE     spec: '>19',
54 warn ERESOLVE     error: 'INVALID',
54 warn ERESOLVE     from: {
54 warn ERESOLVE       name: '@chainsafe/dappeteer',
54 warn ERESOLVE       version: '5.0.0',
54 warn ERESOLVE       location: 'node_modules/@chainsafe/dappeteer',
54 warn ERESOLVE       isWorkspace: false,
54 warn ERESOLVE       dependents: [Array]
54 warn ERESOLVE     }
54 warn ERESOLVE   },
54 warn ERESOLVE   dep: {
54 warn ERESOLVE     name: 'puppeteer',
54 warn ERESOLVE     version: undefined,
54 warn ERESOLVE     errors: [ [Error] ],
54 warn ERESOLVE     package: {},
54 warn ERESOLVE     whileInstalling: {
54 warn ERESOLVE       name: '@chainsafe/dappeteer',
54 warn ERESOLVE       version: '5.0.0',
54 warn ERESOLVE       path: '/Users/maoxiandaozhenhaowan/Desktop/Code/auto-blur/node_modules/@chainsafe/dappeteer'
54 warn ERESOLVE     },
54 warn ERESOLVE     location: 'node_modules/puppeteer',
54 warn ERESOLVE     isWorkspace: false,
54 warn ERESOLVE     dependents: [ [Object] ]
54 warn ERESOLVE   },
54 warn ERESOLVE   force: false,
54 warn ERESOLVE   isMine: true,
54 warn ERESOLVE   strictPeerDeps: false,
54 warn ERESOLVE   current: {
54 warn ERESOLVE     name: 'puppeteer',
54 warn ERESOLVE     version: '19.7.2',
54 warn ERESOLVE     location: 'node_modules/puppeteer',
54 warn ERESOLVE     isWorkspace: false,
54 warn ERESOLVE     dependents: [ [Object] ]
54 warn ERESOLVE   }
54 warn ERESOLVE }
55 warn ERESOLVE overriding peer dependency {
55 warn ERESOLVE   code: 'ERESOLVE',
55 warn ERESOLVE   edge: {
55 warn ERESOLVE     type: 'peerOptional',
55 warn ERESOLVE     name: 'puppeteer',
55 warn ERESOLVE     spec: '>19',
55 warn ERESOLVE     error: 'INVALID',
55 warn ERESOLVE     from: {
55 warn ERESOLVE       name: '@chainsafe/dappeteer',
55 warn ERESOLVE       version: '5.0.0',
55 warn ERESOLVE       location: 'node_modules/@chainsafe/dappeteer',
55 warn ERESOLVE       isWorkspace: false,
55 warn ERESOLVE       dependents: [Array]
55 warn ERESOLVE     }
55 warn ERESOLVE   },
55 warn ERESOLVE   dep: {
55 warn ERESOLVE     name: 'puppeteer',
55 warn ERESOLVE     version: undefined,
55 warn ERESOLVE     errors: [ [Error] ],
55 warn ERESOLVE     package: {},
55 warn ERESOLVE     whileInstalling: {
55 warn ERESOLVE       name: '@chainsafe/dappeteer',
55 warn ERESOLVE       version: '5.0.0',
55 warn ERESOLVE       path: '/Users/maoxiandaozhenhaowan/Desktop/Code/auto-blur/node_modules/@chainsafe/dappeteer'
55 warn ERESOLVE     },
55 warn ERESOLVE     location: 'node_modules/puppeteer',
55 warn ERESOLVE     isWorkspace: false,
55 warn ERESOLVE     dependents: [ [Object] ]
55 warn ERESOLVE   },
55 warn ERESOLVE   force: false,
55 warn ERESOLVE   isMine: true,
55 warn ERESOLVE   strictPeerDeps: false,
55 warn ERESOLVE   current: {
55 warn ERESOLVE     name: 'puppeteer',
55 warn ERESOLVE     version: undefined,
55 warn ERESOLVE     errors: [ [Error] ],
55 warn ERESOLVE     package: {},
55 warn ERESOLVE     location: 'node_modules/puppeteer',
55 warn ERESOLVE     isWorkspace: false,
55 warn ERESOLVE     dependents: [ [Object] ]
55 warn ERESOLVE   }
55 warn ERESOLVE }
56 timing idealTree:node_modules/@chainsafe/dappeteer Completed in 8ms
57 timing idealTree:#root Completed in 0ms
58 timing idealTree:node_modules/puppeteer Completed in 0ms
59 timing idealTree:buildDeps Completed in 979ms
60 timing idealTree:fixDepFlags Completed in 1ms
61 timing idealTree Completed in 1024ms
62 timing command:install Completed in 1027ms
63 verbose type range
64 verbose stack puppeteer: No matching version found for puppeteer@>19.
64 verbose stack     at module.exports (/Users/maoxiandaozhenhaowan/.nvm/versions/node/v19.6.1/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
64 verbose stack     at RegistryFetcher.manifest (/Users/maoxiandaozhenhaowan/.nvm/versions/node/v19.6.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
65 verbose cwd /Users/maoxiandaozhenhaowan/Desktop/Code/auto-blur
66 verbose Darwin 22.2.0
67 verbose node v19.6.1
68 verbose npm  v9.5.0
69 error code ETARGET
70 error notarget No matching version found for puppeteer@>19.
71 error notarget In most cases you or one of your dependencies are requesting
71 error notarget a package version that doesn't exist.
72 verbose exit 1
73 timing npm Completed in 1047ms
74 verbose unfinished npm timer reify 1677035665649
75 verbose unfinished npm timer reify:loadTrees 1677035665651
76 verbose code 1
77 error A complete log of this run can be found in:
77 error     /Users/maoxiandaozhenhaowan/.npm/_logs/2023-02-22T03_14_25_629Z-debug-0.log
```

**Comment by BeroBurny** [comment]
We just released version `5.0.1` which should fix that issue
