### ISSUE TITLE
Have trouble starting metamask

### ISSUE THREAD

**Issue by HelloWeb3World** [ChainSafe/dappeteer#311]
**Describe the bug**
I get a lot of error when setup matamask (like 8/10)
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/112918089/234027585-1f5bc4b5-dae3-4dac-8682-fe1b726b1564.png">

**To Reproduce**
        const browser = await dappeteer.launch({
            headless: false,
        })
            const metaMask = await dappeteer.setupMetaMask(browser, {
                seed: "test test test test test test test test test test test junk",
                password: "xxx",
            });

**Logs**
```shell
Some Logs from console
```

**Expected behavior**
can setup metamask successfully

**Screenshots**

**System:**
- MacOs
- OS version 13.3.1
- NodeJs version v18.14.2
- dappeteer version 5.0.1
- testing framework 
- testing framework version 
- puppeteer version 19.10.1
- playwright version 

**Additional context**

**Comment by stefan-girlich** [comment]
Same issue for 100% of attempts. This error is logged in Chrome DevTools; not sure if related:
```
s:76 Error: No response from RPC
  at ui-10.js:1:258405
  at s (sentry-install.js:1:12302)
(anonymous) @ s
```

**Comment by BeroBurny** [comment]
Hey @HelloWeb3World  and @stefan-girlich

Currently, there is resealing a new version `5.1.0`, that version will have the latest MetaMask version, and is possible that will solve the issue running it.
If is issue still present can I get some reproducting repository?

**Comment by stefan-girlich** [comment]
Thanks for the prompt reponse, @BeroBurny .
Happy to try out the new version; would you know when it will be published on npm?

**Comment by stefan-girlich** [comment]
@BeroBurny - would you know when 5.1.0 is available via npm? thx!

**Comment by BeroBurny** [comment]
Hey, sorry for the delay (weekend, and stuff).
Had a problem with ci for releasing `5.1.0` but fixed it and released `5.1.1`

**Comment by KIttojo** [comment]
I have such params at config

```
  "dependencies": {
    "@chainsafe/dappeteer": "^5.1.1",
    "puppeteer-core": "^20.2.1"
  }
```

But this problem still occurs. When fix, sir?

<img width="888" alt="image" src="https://github.com/ChainSafe/dappeteer/assets/45813478/5440bf97-8400-4c41-8d50-b9ee6f73ed5d">

**Comment by sofianeOuafir** [comment]
same issue here, any work around?

**Comment by Evan-Baekdu** [comment]
Any solution?

**Comment by mint-pz** [comment]
I tried to reload the metamask page and here is my workaround code: 

```js
const browser = await dappeteer.launch({ headless: false })

 await sleep(2000)

    const pages = await browser.pages()
    for (const page of pages) {
        if (page.url().startsWith('chrome-extension')) {
            await sleep(2000)
            await page.reload()
        }
    }

await sleep(2000)

const metaMask = await dappeteer.setupMetaMask(browser, {
seed: "test test test test test test test test test test test junk",
password: "xxx",
});
```
