### ISSUE TITLE
Version v10.31.0 (flask: false) not found!

### ISSUE THREAD

**Issue by sunchengzhu** [ChainSafe/dappeteer#351]
**Describe the bug**
Today, I found that I am unable to download version 10.31.0 of MetaMask.
**To Reproduce**
``` bash
git clone https://github.com/axonweb3/axon.git
cd axon/tests/e2e
yarn install
echo '\n' | yarn http-server
yarn test
```

**Logs**
```shell
Searching for MetaMask release
Error: Jest: Got error running globalSetup - /home/runner/work/axon/axon/tests/e2e/jest/setup.js, reason: "Version v10.31.0 (flask: false) not found!"
    at runGlobalHook (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/runGlobalHook.js:117:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runJest (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/runJest.js:327:5)
    at async _run10000 (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/cli/index.js:344:7)
    at async runCLI (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/cli/index.js:199:3)
    at async Object.run (/home/runner/work/axon/axon/tests/e2e/node_modules/jest-cli/build/run.js:124:37)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 FAIL  Attempt: 3/3; next in 61ms
Error: Error: Jest: Got error running globalSetup - /home/runner/work/axon/axon/tests/e2e/jest/setup.js, reason: "Version v10.31.0 (flask: false) not found!"
    at runGlobalHook (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/runGlobalHook.js:117:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runJest (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/runJest.js:327:5)
    at async _run10000 (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/cli/index.js:344:7)
    at async runCLI (/home/runner/work/axon/axon/tests/e2e/node_modules/@jest/core/build/cli/index.js:199:3)
    at async Object.run (/home/runner/work/axon/axon/tests/e2e/node_modules/jest-cli/build/run.js:124:37)
error Command failed with exit code 1.
    at file:///home/runner/work/axon/axon/tests/e2e/zx-zc08kxkkov.mjs:1:37
    exit code: 1
Error: Process completed with exit code 1.
```

**Additional context**
I've noticed that [the dappeteer version](https://github.com/ChainSafe/dappeteer/releases/tag/v5.2.0) has not been updated for a long time (last update was in May 2023). Could this be related? Please help me check.

**Comment by JornTeurlings** [comment]
Perhaps of little help for a fix for you, but for me setting the version to 10.32.0 resolved the issue and lets me use the application as intended. Hope it helps!

**Comment by RaphaelDeLaGhetto** [comment]
> Perhaps of little help for a fix for you, but for me setting the version to 10.32.0 resolved the issue and lets me use the application as intended. Hope it helps!

Just ran into this today. I glanced at the download `metamask` script, but I didn't see any mention of a version. How did you bump it to `10.32.0`?

The world needs more `dappeteer`!

**Comment by JornTeurlings** [comment]
> > Perhaps of little help for a fix for you, but for me setting the version to 10.32.0 resolved the issue and lets me use the application as intended. Hope it helps!
> 
> Just ran into this today. I glanced at the download `metamask` script, but I didn't see any mention of a version. How did you bump it to `10.32.0`?
> 
> The world needs more `dappeteer`!

There is a parameter that you can give to the dappeteer.launch which takes in a parameter metaMaskVersion. To this you give the version that you would like to use, which in my case was 10.32.0.
