### ISSUE TITLE
Unable to dismiss "What's New" modal in Metamask

### ISSUE THREAD

**Issue by 0xJem** [ChainSafe/dappeteer#61]
**Describe the problem**

After calling the approve() function, the window switches to Metamask. However, it displays a modal window for "What's New". I am unable to dismiss this. Has anyone experienced this? Or is there a way we can dismiss it automatically?

![Screenshot 2021-11-05 at 4 55 26 PM](https://user-images.githubusercontent.com/91760036/140507337-91af7fa6-0cc1-4c63-91ec-ab8de29df508.png)

It ends up timing out:
```
Running tests on MetaMask version v10.1.1

/Users/xxx/Documents/Work/olympus-frontend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:517
            const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: waiting for selector `button.button.btn-primary` failed: timeout 30000ms exceeded
    at new WaitTask (/Users/xxx/Documents/Work/olympus-frontend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:517:34)
    at DOMWorld.waitForSelectorInPage (/Users/xxx/Documents/Work/olympus-frontend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:428:26)
    at Object.internalHandler.waitFor (/Users/xxx/Documents/Work/olympus-frontend/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/Users/xxx/Documents/Work/olympus-frontend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:321:29)
    at Frame.waitForSelector (/Users/xxx/Documents/Work/olympus-frontend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:924:51)
    at Page.waitForSelector (/Users/xxx/Documents/Work/olympus-frontend/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2359:33)
    at /Users/xxx/Documents/Work/olympus-frontend/node_modules/@chainsafe/dappeteer/dist/metamask/approve.js:17:31
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/Documents/Work/olympus-frontend/node_modules/@chainsafe/dappeteer/dist/metamask/approve.js:5:58)
```

**System:**
- OS: MacOS
- OS version: 12.0.1
- NodeJs version: 17.0.1
- dAppeteer version: 2.2.0
- testing framework: none
- testing framework version: none

**Example Code**
```const page = await browser.newPage();
  await page.goto("http://localhost:3000/#/stake");

  await clickElement(page, ".connect-button");

  await metamask.approve();

  await metamask.reload();
  const metamaskPopup = await metamask.page.waitForSelector("button.popover-header__button");
  await metamaskPopup.click();
```

I've also tried:
`await metamask.page.waitForSelector(".popover-header__button");`
`await metamask.page.waitForSelector("[title='Close']");`

**Comment by BeroBurny** [comment]
Hello @0xJem thanks for reaching out.

Did you use [`await dappeteer.setupMetamask(browser);`](https://github.com/ChainSafe/dappeteer/blob/master/docs/API.md#setup) after `await dappeteer.launch(puppeteer, { metamaskVersion: 'v10.1.1' });` like in example from [readme](https://github.com/ChainSafe/dappeteer#usage)

**Comment by 0xJem** [comment]
Yes, here's the code from the start of the test function:
```
  const browser = await dappeteer.launch(puppeteer, { metamaskVersion: "v10.1.1" });

  const metamask = await dappeteer.setupMetamask(browser, { seed: "ZZZ" });
  await metamask.switchNetwork("rinkeby");

  const page = await browser.newPage();
  await page.goto("http://localhost:3000/#/stake");

  await clickElement(page, ".connect-button");

  await metamask.approve();

  await metamask.reload();
  const metamaskPopup = await metamask.page.waitForSelector("button.popover-header__button");
  await metamaskPopup.click();
```

**Comment by 0xJem** [comment]
Right, I was able to dismiss the "What's New" modal:
```
  const browser = await dappeteer.launch(puppeteer, { metamaskVersion: "v10.1.1" });

  const metamask = await dappeteer.setupMetamask(browser, { seed: "ZZZ" });
  await metamask.switchNetwork("rinkeby");

  const page = await browser.newPage();
  await page.goto("http://localhost:3000/#/stake");

  await clickElement(page, ".connect-button");

  // Approve connecting the wallet
  // We don't `await` the approve() function, as it will never return.
  metamask.approve();
  // Close the "What's New" modal that appears in MetaMask
  const metamaskPopup = await metamask.page.waitForSelector(".fas.fa-times.popover-header__button");
  await metamaskPopup.click();
```

However, the approval modal never appears in the metamask interface. Am I doing something wrong?

**Comment by 0xJem** [comment]
For context, I am trying to mimic the user pressing the "connect" button in the web3 app, and choosing which account to connect in metamask.

**Comment by 0xJem** [comment]
Ah, turns out I was doing it incorrectly. The Metamask/WalletConnect modal was still visible in the web3 app interface, and it needed to be clicked. The working code (including approval):
```
const browser = await dappeteer.launch(puppeteer, { metamaskVersion: "v10.1.1" });

  const metamask = await dappeteer.setupMetamask(browser, { seed: "ZZZ" });
  await metamask.switchNetwork("rinkeby");

  const page = await browser.newPage();
  await page.goto("http://localhost:3000/#/stake");

  // Connect button
  await clickElement(page, ".connect-button");

  // Metamask/Wallet Connect modal window
  await clickElement(page, ".web3modal-provider-wrapper");

  // Approve connecting the wallet
  await metamask.approve();
```

**Comment by cinjon** [comment]
Hmm, I did the above and the welcome message is still sticking around. The test below passes but the metamask window still has that message and so it interferes when I try to do `await metamask.confirmTransaction`. 

```
  it('visits the homepage and logs into web3sso.', async () => {      
    await newPage.goto('http://localhost:3000')
    await clickElement(newPage, '#web3SSO')
    await clickElement(newPage, ".web3modal-provider-wrapper");
    await metamask.approve();

    await newPage.bringToFront()
    await newPage.waitForSelector('#web3Address')

    const text = await getText(newPage, '#web3Address')
    await expect(text).toEqual('0xf39F')
  })
```

**Comment by cinjon** [comment]
@0xJem any idea what's up above? Did you change anything else?

**Comment by cinjon** [comment]
Looks like it operates no problem w/o it going away.
